apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    networking.knative.dev/http-protocol: "redirected"
spec:
  ingress:
    istio:
      enabled: false
  config:
    domain:
      "knative.192.168.1.90.nip.io": ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"

